# Task 1: Build a basic machine learning pipeline

Choose one of the provided datasets and complete the main pipeline steps in Jupyter Notebook or Google Colab:

- Load and inspect the dataset
- Understand the business problem
- Identify the features and target variable
- Define X and y
- Clean the data
- Handle missing values
- Handle categorical and numerical variables
- Split the data into training and testing sets
- Apply preprocessing
- Train a simple baseline model using Logistic Regression

In [1]:
# Load the dataset 

import pandas as pd 

df = pd.read_csv("investment_product_subscription_dataset.xls")

df.head()

,Customer_ID,Age,Employment_Status,Annual_Income,Account_Balance,Risk_Tolerance,Previous_Investments,Advisor_Contacted,Mobile_Banking_User,Financial_Literacy_Score,Marketing_Email_Opened,Number_of_Bank_Products,Subscribed_Investment_Product
0,1,28.0,Part-time,189900.0,185575.0,Medium,No,Yes,Yes,3,Yes,7,Yes
1,2,61.0,Self-employed,57470.0,184258.0,Low,No,Yes,Yes,3,NaN,2,No
2,3,27.0,Student,27164.0,50417.0,Medium,No,Yes,Yes,6,No,1,Yes
3,4,35.0,Student,112229.0,182140.0,Low,No,No,Yes,9,No,5,No
4,5,76.0,Student,149913.0,160977.0,High,Yes,Yes,Yes,1,Yes,1,Yes

In [3]:
# Inspect the dataset 

# Display the first 5 rows of the dataset 
df.head()

,Customer_ID,Age,Employment_Status,Annual_Income,Account_Balance,Risk_Tolerance,Previous_Investments,Advisor_Contacted,Mobile_Banking_User,Financial_Literacy_Score,Marketing_Email_Opened,Number_of_Bank_Products,Subscribed_Investment_Product
0,1,28.0,Part-time,189900.0,185575.0,Medium,No,Yes,Yes,3,Yes,7,Yes
1,2,61.0,Self-employed,57470.0,184258.0,Low,No,Yes,Yes,3,NaN,2,No
2,3,27.0,Student,27164.0,50417.0,Medium,No,Yes,Yes,6,No,1,Yes
3,4,35.0,Student,112229.0,182140.0,Low,No,No,Yes,9,No,5,No
4,5,76.0,Student,149913.0,160977.0,High,Yes,Yes,Yes,1,Yes,1,Yes

In [5]:
# Show the number of rows and columns in the dataset
df.shape

(377, 13)

In [6]:
# Display the names of all columns in the dataset
df.columns

Index(['Customer_ID', 'Age', 'Employment_Status', 'Annual_Income',
       'Account_Balance', 'Risk_Tolerance', 'Previous_Investments',
       'Advisor_Contacted', 'Mobile_Banking_User', 'Financial_Literacy_Score',
       'Marketing_Email_Opened', 'Number_of_Bank_Products',
       'Subscribed_Investment_Product'],
      dtype='object')

In [7]:
# Show general information about the dataset. This includes column names, non-null values, and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Customer_ID                    377 non-null    int64
 1   Age                            370 non-null    float64
 2   Employment_Status              370 non-null    object
 3   Annual_Income                  370 non-null    float64
 4   Account_Balance                370 non-null    float64
 5   Risk_Tolerance                 370 non-null    object
 6   Previous_Investments           377 non-null    object
 7   Advisor_Contacted              377 non-null    object
 8   Mobile_Banking_User            377 non-null    object
 9   Financial_Literacy_Score       377 non-null    int64
 10  Marketing_Email_Opened         370 non-null    object
 11  Number_of_Bank_Products        377 non-null    int64
 12  Subscribed_Investment_Product  377 non-null    object
dtypes: float64(3), int64(3), object(7)
memory usage: 38.4+ KB

In [8]:
# Display the data type of each column
df.dtypes

Customer_ID                        int64
Age                              float64
Employment_Status                 object
Annual_Income                    float64
Account_Balance                  float64
Risk_Tolerance                    object
Previous_Investments              object
Advisor_Contacted                 object
Mobile_Banking_User               object
Financial_Literacy_Score           int64
Marketing_Email_Opened            object
Number_of_Bank_Products            int64
Subscribed_Investment_Product     object
dtype: object

# Understand the Business Problem

**Business Problem**: In this dataset, a bank wants to predict which customers are likely to subscribe to an investment product so it can improve marketing strategies and target the right customers.  
**Machine Learning Problem**: The target column is `Subscribed_Investment_Product` and the value of this column is either `Yes` or `No`. Because we are predicting one of two categories, this is a **Binary Classification**.   
**Prediction Goal**: Predict whether a customer will subscribe to an investment product based on demographic, financial, and behavioral information

In [9]:
business_problem = "A bank wants to predict which customers are likely to subscribe to an investment product."

ml_problem = "This is a classification problem because we want to predict whether a customer will subscribe to an investment product or not." 
 
prediction_goal = "Predict whether a customer will subscribe to an investment product: Yes or No."

# Display the problem definition
print("Business Problem:")
print(business_problem)

print("\nMachine Learning Problem:")
print(ml_problem)

print("\nPrediction Goal:")
print(prediction_goal)

Business Problem:
A bank wants to predict which customers are likely to subscribe to an investment product.

Machine Learning Problem:
This is a classification problem because we want to predict whether a customer will subscribe to an investment product or not.

Prediction Goal:
Predict whether a customer will subscribe to an investment product: Yes or No.

# Identify Features and Target variables

Features (X) include:
- Age
- Employment_Status
- Annual_Income
- Account_Balance
- Risk_Tolerance
- Previous_Investments
- Advisor_Contacted
- Mobile_Banking_User
- Financial_Literacy_Score
- Marketing_Email_Opened
- Number_of_Bank_Products   


Target (y) include:
- Subscribed_Investment_Product


X = Customer information    
y = Subscription decision

In [12]:
# Define X and y 

# Define the feature columns 
feature_columns = [
    "Age",
    "Employment_Status",
    "Annual_Income",
    "Account_Balance",
    "Risk_Tolerance",
    "Previous_Investments",
    "Advisor_Contacted",
    "Mobile_Banking_User",
    "Financial_Literacy_Score",
    "Marketing_Email_Opened",
    "Number_of_Bank_Products" 
]

# Define X as the feature matrix 
X = df[feature_columns]

# Define y as the target variable
y = df["Subscribed_Investment_Product"]

# Display the first 5 rows of X
print("Features (X):")
display(X.head())

# Display the first 5 values of y
print("Target (y):")
display(y.head())

# Check the shape of X and y

# X should have rows and feature columns
print("\nShape of X:", X.shape)

# y should have only rows
print("Shape of y:", y.shape)

Features (X):

,Age,Employment_Status,Annual_Income,Account_Balance,Risk_Tolerance,Previous_Investments,Advisor_Contacted,Mobile_Banking_User,Financial_Literacy_Score,Marketing_Email_Opened,Number_of_Bank_Products
0,28.0,Part-time,189900.0,185575.0,Medium,No,Yes,Yes,3,Yes,7
1,61.0,Self-employed,57470.0,184258.0,Low,No,Yes,Yes,3,NaN,2
2,27.0,Student,27164.0,50417.0,Medium,No,Yes,Yes,6,No,1
3,35.0,Student,112229.0,182140.0,Low,No,No,Yes,9,No,5
4,76.0,Student,149913.0,160977.0,High,Yes,Yes,Yes,1,Yes,1

Target (y):

0    Yes
1     No
2    Yes
3     No
4    Yes
Name: Subscribed_Investment_Product, dtype: object

Shape of X: (377, 11)
Shape of y: (377,)

In [13]:
# Data Cleaning 

# Create a copy of the original dataset before cleaning
df_clean = df.copy()

# Display the number of missing values in each column
print("Missing values before cleaning:")
print(df_clean.isnull().sum())

# Display the number of duplicate rows in the dataset
print("\nNumber of duplicate rows before cleaning:")
print(df_clean.duplicated().sum())

# Display the data type of each column
print("\nData types before cleaning:")
print(df_clean.dtypes)

Missing values before cleaning:
Customer_ID                      0
Age                              7
Employment_Status                7
Annual_Income                    7
Account_Balance                  7
Risk_Tolerance                   7
Previous_Investments             0
Advisor_Contacted                0
Mobile_Banking_User              0
Financial_Literacy_Score         0
Marketing_Email_Opened           7
Number_of_Bank_Products          0
Subscribed_Investment_Product    0
dtype: int64

Number of duplicate rows before cleaning:
7

Data types before cleaning:
Customer_ID                        int64
Age                              float64
Employment_Status                 object
Annual_Income                    float64
Account_Balance                  float64
Risk_Tolerance                    object
Previous_Investments              object
Advisor_Contacted                 object
Mobile_Banking_User               object
Financial_Literacy_Score           int64
Marketing_Email_Opened            object
Number_of_Bank_Products            int64
Subscribed_Investment_Product     object
dtype: object

In [14]:
# Fill missing values in the Age column with the median age
df_clean["Age"] = df_clean["Age"].fillna(df_clean["Age"].median())

# Fill missing values in the Employment Status column with the most frequent status
df_clean["Employment_Status"] = df_clean["Employment_Status"].fillna(df_clean["Employment_Status"].mode()[0])

# Fill missing values in the Annual Income column with the median annual income
df_clean["Annual_Income"] = df_clean["Annual_Income"].fillna(df_clean["Annual_Income"].median())

# Fill missing values in the Account Balance column with the median account balance
df_clean["Account_Balance"] = df_clean["Account_Balance"].fillna(df_clean["Account_Balance"].median())

# Fill missing values in the Risk_Tolerance column with the most frequent risk tolerance
df_clean["Risk_Tolerance"] = df_clean["Risk_Tolerance"].fillna(df_clean["Risk_Tolerance"].mode()[0])

# Fill missing values in the Marketing_Email_Opened column with the most frequent marketing email opened
df_clean["Marketing_Email_Opened"] = df_clean["Marketing_Email_Opened"].fillna(df_clean["Marketing_Email_Opened"].mode()[0])

# Remove duplicate rows from the dataset
# This keeps only one copy of repeated records
df_clean = df_clean.drop_duplicates()

# Display the dataset after removing duplicates
df_clean.head()

,Customer_ID,Age,Employment_Status,Annual_Income,Account_Balance,Risk_Tolerance,Previous_Investments,Advisor_Contacted,Mobile_Banking_User,Financial_Literacy_Score,Marketing_Email_Opened,Number_of_Bank_Products,Subscribed_Investment_Product
0,1,28.0,Part-time,189900.0,185575.0,Medium,No,Yes,Yes,3,Yes,7,Yes
1,2,61.0,Self-employed,57470.0,184258.0,Low,No,Yes,Yes,3,Yes,2,No
2,3,27.0,Student,27164.0,50417.0,Medium,No,Yes,Yes,6,No,1,Yes
3,4,35.0,Student,112229.0,182140.0,Low,No,No,Yes,9,No,5,No
4,5,76.0,Student,149913.0,160977.0,High,Yes,Yes,Yes,1,Yes,1,Yes

In [15]:
# Convert Customer_ID to integer
# Customer_ID is an identifier, not a prediction feature
df_clean["Customer_ID"] = df_clean["Customer_ID"].astype(int)

# Convert Age to integer
df_clean["Age"] = df_clean["Age"].astype(int)

# Convert Annual_Income to float
df_clean["Annual_Income"] = df_clean["Annual_Income"].astype(float)

# Convert Account_Balance to float
df_clean["Account_Balance"] = df_clean["Account_Balance"].astype(float)

# Convert Financial_Literacy_Score to integer
df_clean["Financial_Literacy_Score"] = df_clean["Financial_Literacy_Score"].astype(int)

# Convert Number_of_Bank_Products to integer
df_clean["Number_of_Bank_Products"] = df_clean["Number_of_Bank_Products"].astype(int)

# Convert categorical columns to category type
# This helps us clearly separate categorical variables from numerical variables
df_clean["Employment_Status"] = df_clean["Employment_Status"].astype("category")
df_clean["Risk_Tolerance"] = df_clean["Risk_Tolerance"].astype("category") 
df_clean["Previous_Investments"] = df_clean["Previous_Investments"].astype("category")
df_clean["Advisor_Contacted"] = df_clean["Advisor_Contacted"].astype("category")
df_clean["Mobile_Banking_User"] = df_clean["Mobile_Banking_User"].astype("category")
df_clean["Marketing_Email_Opened"] = df_clean["Marketing_Email_Opened"].astype("category")
df_clean["Subscribed_Investment_Product"] = df_clean["Subscribed_Investment_Product"].astype("category")

# Display data types after cleaning
print("Data types after cleaning:")
print(df_clean.dtypes)

Data types after cleaning:
Customer_ID                         int64
Age                                 int64
Employment_Status                category
Annual_Income                     float64
Account_Balance                   float64
Risk_Tolerance                   category
Previous_Investments             category
Advisor_Contacted                category
Mobile_Banking_User              category
Financial_Literacy_Score            int64
Marketing_Email_Opened           category
Number_of_Bank_Products             int64
Subscribed_Investment_Product    category
dtype: object

C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Customer_ID"] = df_clean["Customer_ID"].astype(int)
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Age"] = df_clean["Age"].astype(int)
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Annual_Income"] = df_clean["Annual_Income"].astype(float)
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Account_Balance"] = df_clean["Account_Balance"].astype(float)
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Financial_Literacy_Score"] = df_clean["Financial_Literacy_Score"].astype(int)
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Number_of_Bank_Products"] = df_clean["Number_of_Bank_Products"].astype(int)
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Employment_Status"] = df_clean["Employment_Status"].astype("category")
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Risk_Tolerance"] = df_clean["Risk_Tolerance"].astype("category")
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Previous_Investments"] = df_clean["Previous_Investments"].astype("category")
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Advisor_Contacted"] = df_clean["Advisor_Contacted"].astype("category")
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Mobile_Banking_User"] = df_clean["Mobile_Banking_User"].astype("category")
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Marketing_Email_Opened"] = df_clean["Marketing_Email_Opened"].astype("category")
C:\Users\amand\AppData\Local\Temp\ipykernel_11276\1995423313.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["Subscribed_Investment_Product"] = df_clean["Subscribed_Investment_Product"].astype("category")

In [19]:
# Check missing values again after cleaning
print("Missing values after cleaning:")
print(df_clean.isnull().sum())

# Check duplicate rows again after cleaning
print("\nNumber of duplicate rows after cleaning:")
print(df_clean.duplicated().sum())

# Display the shape of the cleaned dataset
print("\nShape of cleaned dataset:")
print(df_clean.shape)

# Display the first 5 rows of the cleaned dataset
df_clean.head()

Missing values after cleaning:
Customer_ID                      0
Age                              0
Employment_Status                0
Annual_Income                    0
Account_Balance                  0
Risk_Tolerance                   0
Previous_Investments             0
Advisor_Contacted                0
Mobile_Banking_User              0
Financial_Literacy_Score         0
Marketing_Email_Opened           0
Number_of_Bank_Products          0
Subscribed_Investment_Product    0
dtype: int64

Number of duplicate rows after cleaning:
0

Shape of cleaned dataset:
(370, 13)

,Customer_ID,Age,Employment_Status,Annual_Income,Account_Balance,Risk_Tolerance,Previous_Investments,Advisor_Contacted,Mobile_Banking_User,Financial_Literacy_Score,Marketing_Email_Opened,Number_of_Bank_Products,Subscribed_Investment_Product
0,1,28,Part-time,189900.0,185575.0,Medium,No,Yes,Yes,3,Yes,7,Yes
1,2,61,Self-employed,57470.0,184258.0,Low,No,Yes,Yes,3,Yes,2,No
2,3,27,Student,27164.0,50417.0,Medium,No,Yes,Yes,6,No,1,Yes
3,4,35,Student,112229.0,182140.0,Low,No,No,Yes,9,No,5,No
4,5,76,Student,149913.0,160977.0,High,Yes,Yes,Yes,1,Yes,1,Yes

In [23]:
# Replace the original dataframe with the cleaned dataframe
df = df_clean.copy()

In [25]:
# Step 6: Preprocessing

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer 
from sklearn.pipeline import Pipeline

# Define the feature columns
# These are the input variables that the model will use
feature_columns = [
    "Age",
    "Employment_Status",
    "Annual_Income",
    "Account_Balance",
    "Risk_Tolerance",
    "Previous_Investments",
    "Advisor_Contacted",
    "Mobile_Banking_User",
    "Financial_Literacy_Score",
    "Marketing_Email_Opened",
    "Number_of_Bank_Products" 
]

# Define X as the feature matrix 
X = df[feature_columns]

# Define y as the target variable
y = df["Subscribed_Investment_Product"]

# Convert the target variable from text labels to numbers
# "No" becomes 0 and "Yes" becomes 1
y = y.map({"No": 0, "Yes": 1})

In [26]:
# Define numerical features
numerical_features = [
    "Age",
    "Annual_Income",
    "Account_Balance",
    "Financial_Literacy_Score",
    "Number_of_Bank_Products"
]

# Define categorical features
categorical_features = [
    "Employment_Status",
    "Risk_Tolerance",
    "Previous_Investments", 
    "Advisor_Contacted",
    "Mobile_Banking_User", 
    "Marketing_Email_Opened"    
]

In [27]:
# Create a preprocessing object
# StandardScaler will be applied to numerical columns
# OneHotEncoder will be applied to categorical columns
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)


# Display the first 5 rows of the feature matrix
print("Features before preprocessing:")

display(X.head())

Features before preprocessing:

,Age,Employment_Status,Annual_Income,Account_Balance,Risk_Tolerance,Previous_Investments,Advisor_Contacted,Mobile_Banking_User,Financial_Literacy_Score,Marketing_Email_Opened,Number_of_Bank_Products
0,28,Part-time,189900.0,185575.0,Medium,No,Yes,Yes,3,Yes,7
1,61,Self-employed,57470.0,184258.0,Low,No,Yes,Yes,3,Yes,2
2,27,Student,27164.0,50417.0,Medium,No,Yes,Yes,6,No,1
3,35,Student,112229.0,182140.0,Low,No,No,Yes,9,No,5
4,76,Student,149913.0,160977.0,High,Yes,Yes,Yes,1,Yes,1

In [28]:
# Display the first 5 values of the target variable
print("Target after converting Yes/No to 1/0:")

display(y.head())

Target after converting Yes/No to 1/0:

0    1
1    0
2    1
3    0
4    1
Name: Subscribed_Investment_Product, dtype: category
Categories (2, int64): [0, 1]

In [29]:
# Train/Test Split 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Display the shape of the training and testing sets

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (296, 11)
X_test shape: (74, 11)
y_train shape: (296,)
y_test shape: (74,)

In [30]:
# Display the first 5 rows of the training features

print("Training features:")
display(X_train.head())

# Display the first 5 rows of the testing features

print("Testing features:")
display(X_test.head())

Training features:

,Age,Employment_Status,Annual_Income,Account_Balance,Risk_Tolerance,Previous_Investments,Advisor_Contacted,Mobile_Banking_User,Financial_Literacy_Score,Marketing_Email_Opened,Number_of_Bank_Products
161,32,Full-time,122587.0,6840.0,Low,No,No,Yes,2,No,5
348,76,Student,184826.0,123747.0,High,Yes,No,Yes,7,Yes,7
289,63,Part-time,189474.0,101563.0,High,Yes,Yes,Yes,6,No,5
37,32,Full-time,49283.0,42680.0,Medium,Yes,Yes,Yes,8,No,5
20,64,Full-time,56389.0,138357.0,Low,No,No,Yes,1,No,5

Testing features:

,Age,Employment_Status,Annual_Income,Account_Balance,Risk_Tolerance,Previous_Investments,Advisor_Contacted,Mobile_Banking_User,Financial_Literacy_Score,Marketing_Email_Opened,Number_of_Bank_Products
236,44,Full-time,241396.0,156948.0,High,No,Yes,Yes,10,Yes,5
121,34,Self-employed,139591.5,108311.0,Medium,No,No,Yes,3,No,6
130,56,Student,47130.0,176141.0,Medium,Yes,Yes,Yes,6,Yes,7
39,37,Self-employed,104637.0,136634.0,Medium,No,No,No,5,No,3
312,79,Full-time,186993.0,141917.0,Medium,No,No,Yes,6,Yes,4

In [31]:
# Fit the preprocessor only on the training data
# This prevents data leakage from the test set

X_train_processed = preprocessor.fit_transform(X_train)

# Transform the test data using the same preprocessor
# We do not fit the preprocessor again on the test data

X_test_processed = preprocessor.transform(X_test)

In [35]:
# Display the shape before and after preprocessing

print("Before preprocessing:")
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\nAfter preprocessing:")
print("X_train_processed:", X_train_processed.shape)
print("X_test_processed:", X_test_processed.shape)

Before preprocessing:
X_train: (296, 11)
X_test: (74, 11)

After preprocessing:
X_train_processed: (296, 21)
X_test_processed: (74, 21)

In [38]:
# Build a baseline model 

from sklearn.linear_model import LogisticRegression 

# Create a full pipeline: preprocessing + model 
baseline_model = LogisticRegression(max_iter=1000)

In [39]:
# Train the baseline model using the processed training data
# X_train_processed contains the preprocessed features
# y_train contains the correct target labels

baseline_model.fit(X_train_processed, y_train)

LogisticRegression(max_iter=1000)

In [40]:
# Use the trained model to make predictions on the processed test data
# The model has not seen X_test_processed during training

y_pred = baseline_model.predict(X_test_processed)


# Display the predicted values
# 0 means the customer is predicted not to subscribe
# 1 means the customer is predicted to subscribe

print("Predicted values:")
print(y_pred)

Predicted values:
[1 0 1 0 1 0 1 1 1 1 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 1 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 1 0 1 0 1 1 1 0 1 1 0 0 1 0 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1]

In [41]:
# Evaluating the Baseline Model

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

In [42]:
# Calculate the accuracy of the baseline model
accuracy = accuracy_score(y_test, y_pred)

# Display the accuracy score
print("Accuracy:", accuracy)

Accuracy: 0.8108108108108109

In [43]:
# Create the confusion matrix

cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[26  9]
 [ 5 34]]

In [44]:
# Display the confusion matrix as a table

import pandas as pd

cm_table = pd.DataFrame(
    cm,
    index=["Actual No", "Actual Yes"],
    columns=["Predicted No", "Predicted Yes"]
)

cm_table

            Predicted No  Predicted Yes
Actual No             26              9
Actual Yes             5             34

In [45]:
# Calculate precision
# Precision measures how many predicted Yes values were actually Yes
precision = precision_score(y_test, y_pred, zero_division=0)

# Calculate recall
# Recall measures how many actual Yes values were correctly predicted
recall = recall_score(y_test, y_pred, zero_division=0)

# Calculate F1-score
# F1-score balances precision and recall
f1 = f1_score(y_test, y_pred, zero_division=0)

# Display the evaluation results
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Precision: 0.7906976744186046
Recall: 0.8717948717948718
F1-score: 0.8292682926829268

In [46]:
# Display a full classification report
# This includes precision, recall, F1-score, and support for each class

print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=["No", "Yes"], zero_division=0))

Classification Report:
              precision    recall  f1-score   support

          No       0.84      0.74      0.79        35
         Yes       0.79      0.87      0.83        39

    accuracy                           0.81        74
   macro avg       0.81      0.81      0.81        74
weighted avg       0.81      0.81      0.81        74

In [47]:
# Simple model evaluation summary

print("Model Evaluation Summary")
print("------------------------")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

print("\nInterpretation:")
print("The baseline model gives us an initial performance result.")
print("We can use this result as a benchmark for comparing more advanced models later.")

Model Evaluation Summary
------------------------
Accuracy: 0.8108108108108109
Precision: 0.7906976744186046
Recall: 0.8717948717948718
F1-score: 0.8292682926829268

Interpretation:
The baseline model gives us an initial performance result.
We can use this result as a benchmark for comparing more advanced models later.

# Task 2: Explain and submit your work
At the end of your notebook, write a short explanation including:

- What your model is trying to predict
- What dataset you used
- What features and target you selected
- What result you obtained
- One limitation of your model or dataset

# Interpretation of the Model Results

## What the model is trying to predict: 
My model is trying to predict whether a bank customer will subscribe to an investment product, and the bank's goal is to possibly use this prediction to improve its marketing strategy by identifying and targeting customers who are most likely to subscribe, rather than contacting everyone at random. This is a `Binary Classification Problem`

## Dataset Used: 
The dataset used for this project is the **Investment Product Subscription Dataset,** which originally contained 377 rows and 13 columns. After data cleaning, which involved filling in 7 missing values for the affected columns using the median (for numerical columns) and mode (for categorical columns) and removing 7 duplicate rows:

- Age (median)
- Employment_Status (mode)
- Annual_Income (median)
- Account_Balance (median)
- Risk_Tolerance (mode)
- Marketing_Email_Opened (mode)

The final cleaned dataset contained 370 rows and 13 columns.

## Features and Target Variables Defined 
11 features were selected as input variables (X) which were further separated into numerical and categorical features:

a) Numerical_features:
- Age
- Annual_Income
- Account_Balance
- Financial_Literacy_Score
- Number_of_Bank_Products

b) Categorical_features:
- Employment_Status
- Risk_Tolerance
- Previous_Investments
- Advisor_Contacted
- Mobile_Banking_User
- Marketing_Email_Opened

The target variable (y) is **Subscribed_Investment_Product**, encoded as 1 = Yes and 0 = No.

The data was split into 296 rows for training (80%) and 74 rows for testing (20%), with stratification to ensure both classes were proportionally represented in each split. After preprocessing (StandardScaler on numerical features, OneHotEncoder on categorical features), the feature columns expanded from 11 to 21 columns due to one-hot encoding creating a new binary column for each category value.

## Results Obtained

The logistic regression baseline model produced the following evaluation metrics on the 74 unseen test customers:  

### Accuracy (81.1%):  
The model correctly predicted the subscription decision for 60 out of 74 customers. This means roughly 8 in every 10 predictions were correct.

Accuracy = (TP + TN) / (TP + TN + FP + FN)

Where:
- TP = True Positives
- TN = True Negatives
- FP = False Positives
- FN = False Negatives

Accuracy = (34 + 26) / (34 + 26 + 9 + 5)

Accuracy = 60 / 74

Accuracy = 0.811 ~ 81.1%

### Confusion Matrix

|                | Predicted No | Predicted Yes |
|----------------|--------------|----------------|
| **Actual No**  | 26 ✅        | 9 ❌           |
| **Actual Yes** | 5 ❌         | 34 ✅          |

Out of 35 customers who truly did not subscribe, the model correctly identified 26 (True Negatives) but incorrectly flagged 9 as likely subscribers (False Positives), meaning the bank would have wasted marketing effort on 9 customers.
Out of 39 customers who truly did subscribe, the model correctly identified 34 (True Positives) but missed 5 (False Negatives), meaning 5 real subscribers would have been overlooked.

### Precision (79.1%): 
When the model predicted a customer would subscribe, it was correct 79.1% of the time. Out of every 10 customers the model flagged as "Yes", about 8 actually subscribed.

Precision = (TP) / (TP + FP)  

Precision = (34) / (34 + 9)   

Precision = 34 / 43

Precision = 0.791 ~ 79.1%

### Recall (87.2%): 
The model successfully identified 87.2% of all actual subscribers. Out of the 39 customers who truly subscribed, it correctly caught 34. A high recall means fewer real subscribers are being missed.

Recall = (TP) / (TP + FN)

Recall = (34) / (34 + 5)

Recall = 34 / 39

Recall = 0.872 ~ 87.2%

### F1-Score (82.9%): 
The F1-Score balances precision and recall. At 82.9%, it confirms the model performs solidly on both.

F1 = 2 × (Precision × Recall) / (Precision + Recall)

F1 = 2 × (0.791 × 0.872) / (0.791 + 0.872)

F1 = 2 × 0.689 / 1.663

F1 = 0.829 ~ 82.9%

### Classification Report Summary

| Class        | Precision | Recall | F1-Score | Support |
|---------------|-----------|--------|----------|---------|
| No            | 0.84      | 0.74   | 0.79     | 35      |
| Yes           | 0.79      | 0.87   | 0.83     | 39      |
| **Accuracy**  |           |        | 0.81     | 74      |
| Macro Avg     | 0.81      | 0.81   | 0.81     | 74      |
| Weighted Avg  | 0.81      | 0.81   | 0.81     | 74      |

The "Yes" class had stronger recall (87%) than the "No" class (74%), meaning the model is better at identifying actual subscribers than it is at ruling out non-subscribers. Both classes achieved an F1-Score above 79%.

Overall, this is a strong baseline result as the model correctly identifies more customers likely to subscribe and serves as a solid benchmark for comparing more advanced models in the future.

## Limitation of the Model or Dataset

One major limitation is the very small dataset size of only 370 records. With just 74 customers in the test set, the evaluation metrics can be heavily influenced by just a few predictions. For example, those 5 missed subscribers (False Negatives) alone account for nearly 7% of the test set. A larger dataset would produce more stable and reliable metrics. Additionally, Logistic Regression assumes a linear relationship between features and the outcome, which may not capture the complex, real-world interactions between factors like income, risk tolerance, and banking behaviour.